=== ppenumarthi/DB3/db1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2015 sp1 (x64) (http://www.altova.com) by phani (Stonybrook) -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.auditions.com/my-data" targetNamespace="http://www.auditions.com/my-data" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<element name="ShowMarks">
		<complexType>
			<sequence>
				<element name="showDetails" type="vc:showDetailsType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="judge" type="vc:judgeType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="contestant" type="vc:contestantType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="piece" type="vc:pieceType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="showJudge" type="vc:showJudgeType" minOccurs="0" maxOccurs="unbounded"/>
				<element name="score" type="vc:scoreType" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
	<complexType name="showDetailsType">
		<sequence>
			<element name="showId"/>
			<element name="showName"/>
			<element name="showDate"/>
		</sequence>
	</complexType>
	<complexType name="judgeType">
		<sequence>
			<element name="judgeId"/>
			<element name="judgeName"/>
		</sequence>
	</complexType>
	<complexType name="contestantType">
		<sequence>
			<element name="contestantId"/>
			<element name="contestantName"/>
		</sequence>
	</complexType>
	<complexType name="pieceType">
		<sequence>
			<element name="pieceId"/>
			<element name="pieceName"/>
		</sequence>
	</complexType>
	<complexType name="showJudgeType">
		<sequence>
			<element name="showJudgeId"/>
			<element name="showId"/>
			<element name="judgeId"/>
		</sequence>
	</complexType>
	<complexType name="scoreType">
		<sequence>
			<element name="sjId"/>
			<element name="contId"/>
			<element name="pieceId"/>
			<element name="marks"/>
		</sequence>
	</complexType>
</schema>

=== ppenumarthi/DB3/showJudge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (x64) (http://www.altova.com)-->
<ShowMarks xmlns="http://www.auditions.com/my-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.auditions.com/my-data db1.xsd">
<showJudge>
        <showJudgeId> 1 </showJudgeId>
        <showId> 1 </showId>
        <judgeId> 1</judgeId></showJudge><showJudge>
        <showJudgeId> 2 </showJudgeId>
        <showId> 1 </showId>
        <judgeId> 2</judgeId></showJudge><showJudge>
        <showJudgeId> 3 </showJudgeId>
        <showId> 1 </showId>
        <judgeId> 3</judgeId></showJudge><showJudge>
        <showJudgeId> 4 </showJudgeId>
        <showId> 2 </showId>
        <judgeId> 1</judgeId></showJudge><showJudge>
        <showJudgeId> 5 </showJudgeId>
        <showId> 2 </showId>
        <judgeId> 4</judgeId></showJudge><showJudge>
        <showJudgeId> 6 </showJudgeId>
        <showId> 3 </showId>
        <judgeId> 3</judgeId></showJudge><showJudge>
        <showJudgeId> 7 </showJudgeId>
        <showId> 3 </showId>
        <judgeId> 4</judgeId></showJudge><showJudge>
        <showJudgeId> 8 </showJudgeId>
        <showId> 3 </showId>
        <judgeId> 5</judgeId></showJudge><showJudge>
        <showJudgeId> 9 </showJudgeId>
        <showId> 4 </showId>
        <judgeId> 2</judgeId></showJudge><showJudge>
        <showJudgeId> 10 </showJudgeId>
        <showId> 4 </showId>
        <judgeId> 5</judgeId></showJudge><showJudge>
        <showJudgeId> 11 </showJudgeId>
        <showId> 5 </showId>
        <judgeId> 2</judgeId></showJudge><showJudge>
        <showJudgeId> 12 </showJudgeId>
        <showId> 5 </showId>
        <judgeId> 3</judgeId></showJudge><showJudge>
        <showJudgeId> 13 </showJudgeId>
        <showId> 5 </showId>
        <judgeId> 4</judgeId>
    </showJudge>

</ShowMarks>

=== ppenumarthi/DB3/showDetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (x64) (http://www.altova.com)-->
<ShowMarks xmlns="http://www.auditions.com/my-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.auditions.com/my-data db1.xsd">

 <showDetails>
        <showId> 1</showId>
        <showName> Show1</showName>
        <showDate> 20140202</showDate></showDetails><showDetails>
        <showId> 2</showId>
        <showName> Show2</showName>
        <showDate> 20140402</showDate></showDetails><showDetails>
        <showId> 3</showId>
        <showName> Show3</showName>
        <showDate> 20140602</showDate></showDetails><showDetails>
        <showId> 4</showId>
        <showName> Show4</showName>
        <showDate> 20140802</showDate></showDetails><showDetails>
        <showId> 5</showId>
        <showName> Show5</showName>
        <showDate> 20141002</showDate>
    </showDetails>

</ShowMarks>

=== ppenumarthi/DB3/contestant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (x64) (http://www.altova.com)-->
<ShowMarks xmlns="http://www.auditions.com/my-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.auditions.com/my-data db1.xsd">
<contestant>
        <contestantId> 1</contestantId>
        <contestantName> Joe </contestantName></contestant><contestant>
        <contestantId> 2</contestantId>
        <contestantName> Bob </contestantName></contestant><contestant>
        <contestantId> 3</contestantId>
        <contestantName> Mary </contestantName></contestant><contestant>
        <contestantId> 4</contestantId>
        <contestantName> Ann </contestantName></contestant><contestant>
        <contestantId> 5</contestantId>
        <contestantName> Bess </contestantName></contestant><contestant>
        <contestantId> 6</contestantId>
        <contestantName> Tom </contestantName></contestant><contestant>
        <contestantId> 7</contestantId>
        <contestantName> Don </contestantName>
    </contestant>
    </ShowMarks>

=== ppenumarthi/DB3/piece.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (x64) (http://www.altova.com)-->
<ShowMarks xmlns="http://www.auditions.com/my-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.auditions.com/my-data db1.xsd">
<piece>
        <pieceId> 1</pieceId>
        <pieceName> Barcarolle</pieceName> </piece> <piece>
        <pieceId> 2</pieceId>
        <pieceName> Giselle</pieceName></piece> <piece>
        <pieceId> 3</pieceId>
        <pieceName> The Tramp</pieceName></piece> <piece>
        <pieceId> 4</pieceId>
        <pieceName> Besame Mucho</pieceName></piece> <piece>
        <pieceId> 5</pieceId>
        <pieceName> Swan Lake</pieceName></piece> <piece>
        <pieceId> 6</pieceId>
        <pieceName> Habanera</pieceName>
    </piece>
    </ShowMarks>

=== ppenumarthi/DB3/judge.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2015 sp1 (x64) (http://www.altova.com)-->
<ShowMarks xmlns="http://www.auditions.com/my-data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.auditions.com/my-data db1.xsd">
 <judge>
        <judgeId> 1</judgeId>
        <judgeName> Judy</judgeName></judge><judge>
        <judgeId> 2</judgeId>
        <judgeName> Lucy</judgeName></judge><judge>
        <judgeId> 3</judgeId>
        <judgeName> Irving</judgeName></judge><judge>
        <judgeId> 4</judgeId>
        <judgeName> Phil</judgeName></judge><judge>
        <judgeId> 5</judgeId>
        <judgeName> Oscar</judgeName>
    </judge>
</ShowMarks>
